services:
  backend:
    build: ./backend
    container_name: wallpapers_backend
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: wallpapers_frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    container_name: wallpapers_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: wallpapers_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./certbot/certificates:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data: